name: Deploy To Server

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        with:
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SOURCE: 'src/ package.json pnpm-lock.yaml tsconfig.json view/ src/ public/ .npmrc bootstrap.js'
          TARGET: /root/ollah/server
          EXCLUDE: '/dist/, node_modules/'
          SCRIPT_BEFORE: |
            echo $0
          SCRIPT_AFTER: |
            cd /root/ollah/server
            echo 'Check Version'
            node -v
            pnpm -v
            echo 'Use NODE V22'
            echo 'Install Dependence'
            pnpm i
            echo 'Running Server'
            pnpm stop
            pnpm start
