name: Deploy To Test Environment

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SOURCE: .
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
          TARGET: /root/duuk/serve
          EXCLUDE: "/dist/, /node_modules/"
          SCRIPT_BEFORE: |
            echo $PWD
            echo '###start1'
            whoami
            ls -al
          SCRIPT_AFTER: |
            echo $PWD
            echo '###start2'
            whoami
            ls -al
            echo $RSYNC_STDOUT